It kind of works now

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -32,13 +32,18 @@ RUN touch .android/repositories.config
 RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
 RUN unzip sdk-tools.zip && rm sdk-tools.zip
 RUN mv tools Android/sdk/tools
+RUN chown -R $USER_UID:$USER_GID /home/developer/Android
 RUN cd Android/sdk/tools/bin
-RUN yes | ./sdkmanager --licenses
-RUN cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-tools" "platforms;android-29" "sources;android-29"
+RUN mkdir -p "$ANDROID_SDK_ROOT/licenses" 
+RUN echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
+RUN ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-tools" "platforms;android-29" "sources;android-29" || echo "Command failed"
+RUN yes | /home/developer/Android/sdk/tools/bin/sdkmanager --install "cmdline-tools;latest"
 ENV PATH "$PATH:/home/developer/Android/sdk/platform-tools"
 
 # Download the flutter SDK
 RUN git clone https://github.com/flutter/flutter.git /home/developer/flutter/
+RUN chown -R $USER_UID:$USER_GID /home/developer/flutter
 ENV PATH "$PATH:/home/developer/flutter/bin"
 
-#Maybe run flutter doctor and flutter -d web-application
+USER $USERNAME
+RUN cd /home/developer
